name: Tests

on: [push]

permissions:
  contents: read
  id-token: write

jobs:
  minitest:
    strategy:
      matrix:
        ruby-version: ['3.4', '3.3', '3.2']

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby-version }}

      - name: Run all tests
        run: |
          cp .env.example .env
          bin/rake test

      - name: Qlty Coverage Upload
        if: matrix.ruby-version == '3.4'
        uses: qltysh/qlty-action/coverage@v2
        with:
          oidc: true
          files: coverage/coverage.json

  linters:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run all style checks
        run: bin/rubocop --parallel
